### ISSUE TITLE
Dryable does not keep the docstrings

### ISSUE THREAD

**Issue by rgreinho** [haarcuba/dryable#2]
I needed to add a dry-run functionality to one of my tool, and started to use `dryable` to achieve this.

However now, all the functions which can be dried lost their docstrings and do no appear anymore in the documentation generated with Sphinx `automodule`. 

Example with the decorator:
```
>>> import dryable
>>> @dryable.Dryable()
... def saveToRemoteDatabase(results):
...     """This function saves everything into the DB."""
...     print('will now open an real world connection'
...           'that requires a server and will make side effects')
>>> saveToRemoteDatabase.__doc__
>>>
```

Example without:
```
>>> def saveToRemoteDatabase(results):
...     """This function saves everything into the DB."""
...     print('will now open an real world connection'
...           'that requires a server and will make side effects')
>>> saveToRemoteDatabase.__doc__
'This function save everything into the DB.'
>>>
```

The decorator should not alter the docstrings.

Here I found an interesting article talking about this exact problem: https://hynek.me/articles/decorators/

**Comment by haarcuba** [comment]
Thanks! Will fix

**Comment by haarcuba** [comment]
@rgreinho please tell me if this solved your problem

**Comment by rgreinho** [comment]
Unfortunately it did not solve my problem.

I found this workaround though:

I edited the decorator as to use `functools.wraps`:
```python
from functools import wraps
[...]
def __call__( self, function ):
        @wraps(function)
        def _decorated( * args, ** kwargs ):
[...]
        # _decorated.__doc__ = function.__doc__
        # _decorated.__name__ = function.__name__
        return _decorated
```
and then the docstrings appear in my python documentation.

**Comment by haarcuba** [comment]
could you please make it into a pull request?

**Comment by rgreinho** [comment]
Done in #3, but modifying the decorator to make it work with [`wrapt`](https://pypi.org/project/wrapt/) may be a more correct approach.
